/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MiningDevice } from "./MiningDevice";
import { MiningDeviceCountArgs } from "./MiningDeviceCountArgs";
import { MiningDeviceFindManyArgs } from "./MiningDeviceFindManyArgs";
import { MiningDeviceFindUniqueArgs } from "./MiningDeviceFindUniqueArgs";
import { DeleteMiningDeviceArgs } from "./DeleteMiningDeviceArgs";
import { MiningDeviceService } from "../miningDevice.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MiningDevice)
export class MiningDeviceResolverBase {
  constructor(
    protected readonly service: MiningDeviceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MiningDevice",
    action: "read",
    possession: "any",
  })
  async _miningDevicesMeta(
    @graphql.Args() args: MiningDeviceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MiningDevice])
  @nestAccessControl.UseRoles({
    resource: "MiningDevice",
    action: "read",
    possession: "any",
  })
  async miningDevices(
    @graphql.Args() args: MiningDeviceFindManyArgs
  ): Promise<MiningDevice[]> {
    return this.service.miningDevices(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MiningDevice, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MiningDevice",
    action: "read",
    possession: "own",
  })
  async miningDevice(
    @graphql.Args() args: MiningDeviceFindUniqueArgs
  ): Promise<MiningDevice | null> {
    const result = await this.service.miningDevice(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MiningDevice)
  @nestAccessControl.UseRoles({
    resource: "MiningDevice",
    action: "delete",
    possession: "any",
  })
  async deleteMiningDevice(
    @graphql.Args() args: DeleteMiningDeviceArgs
  ): Promise<MiningDevice | null> {
    try {
      return await this.service.deleteMiningDevice(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
